### ISSUE TITLE
Static Assets

### ISSUE THREAD

**Issue by iammerrick** [realpython/dockerizing-django#13]
Any way to let Django serve the static assets if collectstatic hasn't been run yet? It's sort of a pain to run collectstatic each time you know?

**Comment by mjhea0** [comment]
You could add it to a shell script:

``` sh
#!/bin/sh
python /app/manage.py collectstatic --noinput
/usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000
```

Then in the _production.yml_ file just run the shell script:

``` yaml
web:
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
  env_file: .env
  command: /shell-script.sh
```
