### ISSUE TITLE
Admin CSS and static file links are broken

### ISSUE THREAD

**Issue by rchamarthi** [realpython/dockerizing-django#8]
Django uses css files from the contrib/auth directories for it's admin screens. Since this is not part of the mounted static file directories, admin UI is broken.

In my case, the files were in _/usr/local/lib/python2.7/dist-packages/django/contrib_ and I copied the folder to my app'ssource to get it to work. Obviously, this is a hack. Since location of the admin css files is based on the distribution, what is the right way to dockerize this?

**Comment by lukeorland** [comment]
I was able to fix this by doing the following:
1. Replace this [line](https://github.com/realpython/dockerizing-django/blob/a1bf5f365fb12fb3664e4554e1db01b6d94e7adb/docker-compose.yml#L10) in `docker-compose.yml` with 
   
   ```
       - ./web/static:/usr/src/app/static
   ```
2. In `web/docker_django/settings.py` add the line `STATIC_ROOT = 'static'`.
3. After running these two commands:
   
   ```
   docker-compose up -d
   docker-compose run web /usr/local/bin/python manage.py migrate
   ```
   
   run:
   
   ```
   docker-compose run web /usr/local/bin/python manage.py collectstatic --noinput
   ```

I also added

```
  volumes:
    - /usr/src/app/static
```

to `production.yml` so that it mounts a writeable volume that the static files created when working with the dev docker machine get copied to the production docker container (I don't think I fully understand this part yet).

An entry like `static/*` probably ought to be added to `.gitignore`.

**Comment by lukeorland** [comment]
An even better improvement I've found is to instead include this definition in `docker-compose.yml`:

```
  volumes:
    - ./web:/usr/src/app
```

Files I edit on my local filesystem are mirrored on the docker host.

**Comment by mjhea0** [comment]
I agree with @lukeorland solution. I'll edit the blog post later today. Cheers! :+1:

**Comment by mjhea0** [comment]
@lukeorland how's this:

```
web:
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - ./web:/usr/src/app
  env_file: .env
  command: /usr/local/bin/gunicorn docker_django.wsgi:application -w 2 -b :8000

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

postgres:
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"

redis:
  restart: always
  image: redis:latest
  ports:
    - "6379:6379"

data:
  restart: always
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"
```

**Comment by lukeorland** [comment]
That looks good to me for point number 1 in my first [post](https://github.com/realpython/dockerizing-django/issues/8#issuecomment-133888602). It's up to you if you want to talk about `STATIC_ROOT` and `manage.py collectstatic --noinput` (points 2 and 3) in your blog.

**Comment by rchamarthi** [comment]
@lukeorland @mjhea0 - Thanks! 

@lukeorland - how are the static files and directories configured in your set up? I tried a similar idea of mounting the static directory (after I ran collectstatic), but django complained of this error.

http://stackoverflow.com/questions/27213752/collecting-staticfiles-throws-improperlyconfigured

**docker-compose.py**

```
web:
  restart: always
  build: ./web
  expose:
    - "8000"
  links:
    - db:db
  #  - redis:redis
  volumes:
    - web/static2:/usr/src/app/static2
  env_file: .env
  command: bash -c "python manage.py makemigrations && python manage.py migrate && /usr/local/bin/gunicorn django_project.wsgi:application -w 2 -b :8000"
```

**settings.py**

```
STATICFILES_DIRS = (
    os.path.join(SITE_ROOT, 'static'),
)

STATIC_ROOT = 'static2'
STATIC_URL = '/static/'
```

I had to use a `static2` directory instead for serving the files.
